version: "3.9"
services:
  mongodb-express:
    image: mongo-express:latest
    restart: always
    container_name: readme.notification.mongo-express
    ports:
      - 8083:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: test
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: test
      ME_CONFIG_MONGODB_URL: mongodb://admin:test@readme.notification.db:27017/
