services:
  mongodb:
    container_name: readme.notification.db
    restart: "no"
    ports:
      - 27019:27017
    volumes:
      - ./db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: test
      MONGO_INITDB_DATABASE: readme-notification

  rabbitmq:
    container_name: readme.notification.rabbitmq
    restart: "no"
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: test

  fakesmtp:
    container_name: readme.notification.fakesmtp
    restart: "no"
    ports:
      - 8025:8025
      - 1025:8080
