version: "3.9"
services:
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: readme.post.pgadmin
    ports:
      - 8082:80
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: test
      PGADMIN_CONFIG_SERVER_MODE: "False"
